doninfo:
    resource: "@DoninfoBundle/Resources/config/routing.yml"

doninfo_connexion:
    path:       /connexion
    defaults:
        _controller:    DoninfoBundle:Site:connexion

login_check:
    path:       /connexion_check

logout:
    path:       /logout
