# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt
            cost: 13
        DoninfoBundle\Entity\User:
            algorithm: bcrypt
            cost: 13
        DoninfoBundle\Entity\Admin:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        main:
            entity:
                class:    DoninfoBundle\Entity\User
                property: username
    
    firewalls:
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: doninfo_connexion
                check_path: login_check
            logout:
                path:       /logout
                target:     /
            remember_me:
                secret:     "%secret%"

    access_control:
        - { path: ^/annonce, roles: ROLE_USER }
        - { path: ^/post, roles: ROLE_USER }
        - { path: ^/besoins, roles: ROLE_USER }
        - { path: ^/donations, roles: ROLE_USER }
        - { path: ^/membre, roles: ROLE_USER }
