# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        DoninfoBundle\Entity\User: sha512
        DoninfoBundle\Entity\Admin: sha512

    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN:       [ROLE_USER]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        main:
            entity:
                class:    DoninfoBundle\Entity\User
                property: username
    
    firewalls:
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: doninfo_connexion
                check_path: login_check
            logout:
                path:       logout
                target:     /
            remember_me:
                secret:     "%secret%"
