#Connection optionnelle

doninfo_acceuil:
    path:       /
    defaults:
        _controller:    DoninfoBundle:Site:accueil
        
doninfo_infos_donateur:
    path:       /donateur
    defaults:
        _controller:    DoninfoBundle:Site:donateur
        
doninfo_infos_demandeur:
    path:       /demandeur
    defaults:
        _controller:    DoninfoBundle:Site:demandeur
    
doninfo_inscription:
    path:       /inscription
    defaults:
        _controller:    DoninfoBundle:Site:inscription
        
doninfo_contact_public:
    path:       /contact
    defaults:
        _controller:    DoninfoBundle:Site:contactPublic
        
doninfo_mentions:
    path:       /mentions
    defaults:
        _controller:    DoninfoBundle:Site:mentions
  
#Connection obligatoire  

doninfo_infos:
    path:       /infos
    defaults:
        _controller:    DoninfoBundle:Site:infos

doninfo_post:
    path:       /post
    defaults:
        _controller:    DoninfoBundle:Site:postAnnonce

doninfo_index_donations:
    path:       /donations
    defaults:
        _controller:    DoninfoBundle:Site:donations
        
doninfo_annonce:
    path:       /annonce/{id}
    defaults:
        _controller:    DoninfoBundle:Site:annonce
        
doninfo_index_demandes:
    path:       /demandes
    defaults:
        _controller:    DoninfoBundle:Site:demandes
        
doninfo_tuto:
    path:       /tutoriel
    defaults:
        _controller:    DoninfoBundle:Site:tutoriel
        
doninfo_contact_membre:
    path:       /contact-membre
    defaults:
        _controller:    DoninfoBundle:Site:contactMembre
        
#Espace membre

doninfo_membre:
    path:       /membre/{id}
    defaults:
        _controller:    DoninfoBundle:Site:membre
        
doninfo_membre_informations:
    path:       /membre/{id}/informations
    defaults:
        _controller:    DoninfoBundle:Site:infomembre
        
doninfo_membre_suivi:
    path:       /membre/{id}/suivi
    defaults:
        _controller:    DoninfoBundle:Site:suivi
