#Connection optionnelle

doninfo_acceuil:
    path:       /
    defaults:
        _controller:    DoninfoBundle:Site:accueil
        
doninfo_infos_donateur:
    path:       /donateur
    defaults:
        _controller:    DoninfoBundle:Site:donateur
        
doninfo_infos_demandeur:
    path:       /demandeur
    defaults:
        _controller:    DoninfoBundle:Site:demandeur
    
doninfo_inscription:
    path:       /inscription
    defaults:
        _controller:    DoninfoBundle:Site:inscription
        
doninfo_inscription_done:
    path:       /inscription-remerciement
    defaults:
        _controller:    DoninfoBundle:Site:inscriptiondone
        
doninfo_activation:
    path:       /activation/{active_code}
    defaults:
        _controller:    DoninfoBundle:Site:activation
        
doninfo_contact_public:
    path:       /contact
    defaults:
        _controller:    DoninfoBundle:Site:contactPublic
        
doninfo_mentions:
    path:       /mentions
    defaults:
        _controller:    DoninfoBundle:Site:mentions
  
#Connection obligatoire  

doninfo_logout:
    path:       /logout

doninfo_infos:
    path:       /infos
    defaults:
        _controller:    DoninfoBundle:Site:infos

doninfo_post:
    path:       /post
    defaults:
        _controller:    DoninfoBundle:Site:postAnnonce
        
doninfo_annonce:
    path:       /annonce/{id}
    defaults:
        _controller:    DoninfoBundle:Site:annonce
        
doninfo_list_don:
    path:  /don/list/{page}
    defaults: { _controller: DoninfoBundle:Site:list, page: 1 }
    
doninfo_index_donations:
    path:       /donations
    defaults:
        _controller:    DoninfoBundle:Site:donations
        
doninfo_index_demandes:
    path:       /besoins
    defaults:
        _controller:    DoninfoBundle:Site:demandes
        
doninfo_tuto:
    path:       /tutoriel
    defaults:
        _controller:    DoninfoBundle:Site:tutoriel
        
doninfo_contact_membre:
    path:       /contact-membre
    defaults:
        _controller:    DoninfoBundle:Site:contactMembre
        
#Espace membre

doninfo_membre:
    path:       /membre/{id}
    defaults:
        _controller:    DoninfoBundle:Site:membre
    requirements:
        id: \d+
        
doninfo_membre_informations:
    path:       /membre/{id}/informations
    defaults:
        _controller:    DoninfoBundle:Site:infomembre
        
doninfo_membre_suivi:
    path:       /membre/{id}/suivi
    defaults:
        _controller:    DoninfoBundle:Site:suivi
