#Connection optionnelle

doninfo_acceuil:
    path:       /
    defaults:
        _controller:    DoninfoBundle:Site:accueil
        
doninfo_infos_donateur:
    path:       /donateur
    defaults:
        _controller:    DoninfoBundle:Site:donateur
        
doninfo_infos_demandeur:
    path:       /demandeur
    defaults:
        _controller:    DoninfoBundle:Site:demandeur
    
doninfo_inscription:
    path:       /inscription
    defaults:
        _controller:    DoninfoBundle:Site:inscription
        
doninfo_inscription_done:
    path:       /inscription-remerciement
    defaults:
        _controller:    DoninfoBundle:Site:inscriptiondone
        
doninfo_activation:
    path:       /activation/{active_code}
    defaults:
        _controller:    DoninfoBundle:Site:activation
        
doninfo_contact_public:
    path:       /contact
    defaults:
        _controller:    DoninfoBundle:Site:contactPublic
        
doninfo_mentions:
    path:       /mentions
    defaults:
        _controller:    DoninfoBundle:Site:mentions
  
#Connection obligatoire  

doninfo_logout:
    path:       /logout

doninfo_infos:
    path:       /infos
    defaults:
        _controller:    DoninfoBundle:Site:infos

doninfo_post:
    path:       /post
    defaults:
        _controller:    DoninfoBundle:Site:postAnnonce
        
doninfo_annonce:
    path:       /annonce/{id}
    defaults:
        _controller:    DoninfoBundle:Site:annonce
    requirements:
        id: \d+
        
doninfo_annonce_edit:
    path:       /annonce/edit/{id}
    defaults:
        _controller:    DoninfoBundle:Site:editAnnonce
    requirements:
        id: \d+
    
doninfo_index_donations:
    path:       /donations
    defaults:
        _controller:    DoninfoBundle:Site:donations
        
doninfo_index_besoins:
    path:       /besoins
    defaults:
        _controller:    DoninfoBundle:Site:besoins
        
doninfo_tuto:
    path:       /tutoriel
    defaults:
        _controller:    DoninfoBundle:Site:tutoriel
        
doninfo_contact_membre:
    path:       /contact-membre
    defaults:
        _controller:    DoninfoBundle:Site:contactMembre
        
#Espace membre

doninfo_membre:
    path:       /membre/
    defaults:
        _controller:    DoninfoBundle:Site:membre
        
doninfo_membre_favoris:
    path:       /membre/{id}/suivi
    defaults:
        _controller:    DoninfoBundle:Site:favoris
    requirements:
        id: \d+
