services:
    doninfo.inscription:
        class: DoninfoBundle\Inscription\DoninfoInscription
        arguments:
            - "@doctrine"
            - "@security.password_encoder"
    
    doninfo.poster_annonce:
        class: DoninfoBundle\PosterAnnonce\DoninfoPosterAnnonce
        arguments:
            - "@doctrine"
            