services:
    doninfo.inscription:
        class: DoninfoBundle\Inscription\DoninfoInscription
        arguments:
            - "@doctrine"
            - "@security.password_encoder"
    
    doninfo.poster_annonce:
        class: DoninfoBundle\PosterAnnonce\DoninfoPosterAnnonce
        arguments:
            - "@doctrine"
            
    doninfo.send_mail:
        class: DoninfoBundle\SendMail\DoninfoSendMail
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine"
            - "@service_container"
            
    doninfo.send_contact:
        class: DoninfoBundle\SendContact\DoninfoSendContact
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine"
            - "@service_container"
            
    doninfo.recover_mdp:
        class: DoninfoBundle\RecoverMdp\DoninfoRecoverMdp
        arguments:
            - "@mailer"
            - "@twig"
            - "@doctrine"
            - "@service_container"
            
    doninfo.send_message:
        class: DoninfoBundle\SendMessage\DoninfoSendMessage
        arguments:
            - "@doctrine"
    
    doninfo.list_annonce:
        class: DoninfoBundle\ListAnnonce\DoninfoListAnnonce
        arguments:
            - "@doctrine"
            - "@request_stack"
        tags:
            - { name: knp_paginator.injectable, paginator: knp_paginator }
            
    doninfo.list_messages:
        class: DoninfoBundle\ListMessages\DoninfoListMessages
        arguments:
            - "@doctrine"
            - "@request_stack"
        tags:
            - { name: knp_paginator.injectable, paginator: knp_paginator }
    
    doninfo.validator_cp:
        class: DoninfoBundle\Validator\CodepostalValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: doninfo_valid_cp }
            
    doninfo.validator_cmdp:
        class: DoninfoBundle\Validator\CourrielmdpValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: doninfo_valid_cmdp }
 
