<?php

namespace DoninfoBundle\Repository;

/**
 * ContactMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMembreRepository extends \Doctrine\ORM\EntityRepository
{
}
