<?php

namespace DoninfoBundle\Repository;

/**
 * ContactPublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPublicRepository extends \Doctrine\ORM\EntityRepository
{
}
