<?php

namespace DoninfoBundle\Repository;

/**
 * MessageAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
