<?php

namespace DoninfoBundle\Repository;

/**
 * MessageAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMessage ($id)
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->leftJoin('m.annonce', 'a')
            ->addSelect('a')
            ->where('m.id = :id')
                ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getSingleResult();
    }
    
}
