<?php

namespace DoninfoBundle\Repository;

/**
 * ObjetAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
