<?php

namespace DoninfoBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByActivationCode($active_code)
    {
        $qb = $this->createQueryBuilder('u');

        $qb
        ->where('u.activation = :active_code')
        ->setParameter('active_code', $active_code);

        return $qb
        ->getQuery()
        ->getOneOrNullResult();
    }
}
